<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class assignment_question extends MY_PasController{
    function __construct()
    {
        parent::__construct();
        $this->load->model('assignment_question_model');
    } 

    /*
     * Listing of assignment_questions
     */
    function index($asg_id, $type = 'PEER')
    {
        if ($this->check_permission(20)) {
            if ($asg_id) {
                $type=strtoupper($type);
                $data['asg_id'] = $asg_id;
                $data['type'] = $type;
                $data['_view'] = 'pages/assignment_question/index';

                $data['assignment_questions'] = $this->assignment_question_model->get_assignment_question_by_asgid_section($asg_id,$type);
                $this->load->model('Assignment_model');
                $data['all_assignments'] = $this->Assignment_model->get_all_assignments();
                $this->load_header($data);
                $this->load->view('templates/main',$data);
                $this->load_footer($data);
            }
            else {
                redirect('assignmentadmin');
            }
        }
    }

    /*
     * Adding a new assignment_question
     */
    function add($asg_id, $type)
    {   
        if ($this->check_permission(20)) {
            $type=strtoupper($type);
            $data['asg_id'] = $asg_id;
            $data['type'] = $type;
            if (isset($_POST['counter'])) {
                $counter = $this->input->post('counter');
                for ($x = 0; $x <= intval($counter); $x++) {
                    if (isset($_POST['question'.$x])) {
                        $post_data = array (
                            "asg_id" => $this->input->post('asg_id'),
                            "question" => $this->input->post('question'.$x), 
                            "question_section" => $this->input->post('question_section'.$x), 
                            "answer_type" => $this->input->post('answer_type'.$x)
                        );
                        $this->assignment_question_model->add_assignment_question($post_data);
                    }
                }
                redirect('assignment_question/index/'.$asg_id);
            }
            $data['_view'] = 'pages/assignment_question/add';
            $this->load_header($data);
            $this->load->view('templates/main',$data);
            $this->load_footer($data);
        }
    }  

    /*
     * Editing a assignment_question
     */
    function edit($asg_id, $type,$id)
    {   
        if ($this->check_permission(20)) {
            $type=strtoupper($type);
            $data['asg_id'] = $asg_id;
            $data['type'] = $type;
            // check if the assignment_question exists before trying to edit it
            $data['assignment_question'] = $this->assignment_question_model->get_assignment_question($id);
            
            if(isset($data['assignment_question']['id']))
            {
                $this->load->library('form_validation');

                $this->form_validation->set_rules('max','Max number per group','required');
            
                if($this->form_validation->run())     
                {   
                    $params = array(
                        'topic' => $this->input->post('topic'),
                        'max' => $this->input->post('max'),
                        'topic_desc' => $this->input->post('topic_desc'),
                    );

                    $this->assignment_question_model->update_assignment_question($id,$params);            
                    redirect('assignment_question/index/'.$asg_id);
                }
                else
                {
                    $this->load->model('Assignment_model');
                    $data['all_assignments'] = $this->Assignment_model->get_all_assignments();

                    $data['_view'] = 'pages/assignment_question/edit';
                    $this->load_header($data);
                    $this->load->view('templates/main',$data);
                    $this->load_footer($data);
                }
            }
            else
                show_error('The assignment_question you are trying to edit does not exist.');
        }
    } 

    /*
     * Deleting assignment_question
     */
    function remove($asg_id,$type,$id)
    {
        if ($this->check_permission(20)) {
            $type=strtoupper($type);
            $data['asg_id'] = $asg_id;
            $data['type'] = $type;
            $assignment_question = $this->assignment_question_model->get_assignment_question($id);

            // check if the assignment_question exists before trying to delete it
            if(isset($assignment_question['id']))
            {
                $this->assignment_question_model->delete_assignment_question($id);
                redirect('assignment_question/index/'.$asg_id);
            }
            else
                show_error('The assignment_question you are trying to delete does not exist.');
        }
    }
    
    function remove_all($asg_id, $type)
    {
        if ($this->check_permission(20)) {
            $type=strtoupper($type);
            $data['asg_id'] = $asg_id;
            $data['type'] = $type;
            
            $this->assignment_question_model->delete_assignment_question_all($asg_id, $type);
            redirect('assignment_question/index/'.$asg_id.'/'.$type);
        }
    }
    
    function copy_question() 
    {
        if ($this->check_permission(20)) {
            $from_id = $this->input->post('from_id') ;
            $to_id = $this->input->post('to_id') ;
            $question_section = $this->input->post('question_section') ;
            if ($from_id) {
                $this->assignment_question_model->copy_questions($from_id, $to_id);
            }
            redirect('assignment_question/index/'.$to_id.'/'.$question_section);
        }
    }
    
}
