<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Assignment_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get assignment by id
     */
    function get_assignment($id)
    {
        return $this->db->get_where('sv_assignment_staff',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all assignments count
     */
    function get_all_assignments_count()
    {
        $this->db->from('sv_assignment_staff');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all assignments
     */
    function get_all_assignments($params = array())
    {
        $this->db->order_by('id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('sv_assignment_staff')->result_array();
    }
    
    function get_all_assignments_student($username)
    {
        $this->db->order_by('id', 'desc');
        if(isset($username) && !empty($username))
        {
            $this->db->where('username',$username);
            return $this->db->get('sv_assignemnt_student')->result_array();
        }
        return array();
    }
        
    /*
     * function to add new assignment
     */
    function add_assignment($params)
    {
        $params['create_time'] = current_time();
        $params['last_upd_time'] = current_time();
        $this->db->insert('assignment',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update assignment
     */
    function update_assignment($id,$params)
    {
        $params['last_upd_time'] = current_time();
        $this->db->where('id',$id);
        return $this->db->update('assignment',$params);
    }
    
    function is_allow_view_assignment($username, $asg_id) 
    {
        $rtnResult = false;
        $query = $this->db->query("select fn_is_allow_view_assignment('$username', $asg_id) as result ; ");
        $row = $query->row_array();
        if (isset($row))
        {
            if (intval($row['result']) > 0) {
                $rtnResult = true;
            }
        }
        return $rtnResult;
    }
    
    /*
     * function to delete assignment
     */
    function delete_assignment($id)
    {
        $this->db->delete('assignment_deadline',array('asg_id'=>$id));
        $this->db->delete('assignment_mark_criteria',array('asg_id'=>$id));
        $this->db->delete('assignment_question',array('asg_id'=>$id));
        $this->db->delete('assignment_topic_allocation',array('asg_id'=>$id));
        $this->db->delete('assignment_topic',array('assign_id'=>$id));
        $this->db->delete('assignment',array('id'=>$id));
        return 0;
    }
}
