<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Assignment_deadline_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get assignment_deadline by id
     */
    function get_assignment_deadline($id)
    {
        return $this->db->get_where('assignment_deadline',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all assignment_deadlines count
     */
    function get_all_assignment_deadlines_count()
    {
        $this->db->from('assignment_deadline');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all assignment_deadlines
     */
    function get_all_assignment_deadlines($params = array())
    {
        $this->db->order_by('id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('assignment_deadline')->result_array();
    }
        
    /*
     * function to add new assignment_deadline
     */
    function add_assignment_deadline($params)
    {
        $this->db->insert('assignment_deadline',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update assignment_deadline
     */
    function update_assignment_deadline($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('assignment_deadline',$params);
    }
    
    /*
     * function to delete assignment_deadline
     */
    function delete_assignment_deadline($id)
    {
        return $this->db->delete('assignment_deadline',array('id'=>$id));
    }
}
