<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Submission_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    function get_submission_by_group($asg_id, $topic_id)
    {
        return $this->db->get_where('submission',array('asg_id' =>$asg_id, 'topic_id'=>$topic_id))->row_array();
    }
    
    function get_submission_by_student($asg_id, $user_id)
    {
        return $this->db->get_where('submission',array('asg_id' =>$asg_id, 'user_id'=>$user_id))->row_array();
    }
    
    function get_submission_by_asg($asg_id) 
    {
        return $this->db->get_where('submission',array('asg_id' =>$asg_id))->result_array();
    }
    
    function get_submission_history_by_group($asg_id, $topic_id) 
    {
        $this->db->from('submission_log');
        $this->db->where('asg_id', $asg_id);
        $this->db->where('topic_id', $topic_id);
        $this->db->where('action', 'ADD');
        $this->db->order_by("submission_date", "desc");
        $query = $this->db->get(); 
        return $query->result();
    }
    
    function get_submission_history_by_user($asg_id, $user_id) 
    {
        $this->db->from('submission_log');
        $this->db->where('asg_id', $asg_id);
        $this->db->where('user_id', $user_id);
        $this->db->where('action', 'ADD');
        $this->db->order_by("submission_date", "desc");
        $query = $this->db->get(); 
        return $query->result();
    }
    
    function submit_assignment($asg_id, $topic_id, $user_id, $filename)
    {
        $params = array('asg_id'=>$asg_id, 
                        'topic_id'=>$topic_id,
                        'user_id'=>$user_id,
                        'filename'=>$filename,
                        'submission_date'=>current_time()
                        );
        $this->db->insert('submission',$params);
        return $this->db->insert_id();
    }

    
    function delete_submission_by_group($asg_id, $topic_id)
    {
        $this->db->delete('submission',array('asg_id'=>$asg_id, 'topic_id'=>$topic_id));
    }
    
    function delete_submission_by_individual($asg_id, $user_id)
    {
        $this->db->delete('submission',array('asg_id'=>$asg_id, 'user_id'=>$user_id));
    }
}
